// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/28/2026, 11:08:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/rbonon/Documents/GitHub/fortegb/sandbox/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/plugins/**/*.{js,ts,mjs}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/composables/**/*.{js,ts,mjs}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/utils/**/*.{js,ts,mjs}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rbonon/Documents/GitHub/fortegb/sandbox/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;